<?php defined('ABSPATH') || exit; $studios=beautia_studios(); ?>
<!doctype html><html lang="fa-IR" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?><meta name="description" content="بیوتیا؛ مجموعه‌ای از هفت تجربه مستقل برای ناخن، پوست، مو، اسپا، مژه، میکاپ و باربرشاپ."><meta property="og:title" content="بیوتیا — هفت جهانِ زیبایی"><meta property="og:description" content="یک مجموعه، هفت امضا. دموی دلخواهتان را کشف کنید."></head>
<body <?php body_class(); ?>><?php wp_body_open(); ?><a class="skip-link screen-reader-text" href="#content">پرش به محتوا</a>
<div class="pastel-shell"><div class="hub-announcement">یک مجموعه، هفت امضای متفاوت <span>✦</span> به دنیای بیوتیا خوش آمدید</div>
<header class="hub-header"><div class="hub-container"><a href="<?php echo esc_url(home_url('/')); ?>" class="hub-brand"><span>✦</span><strong>بیوتیا<small dir="rtl">مجموعه بیوتیا</small></strong></a><nav aria-label="ناوبری اصلی"><a href="#collection">دموها</a><a href="#details">جزئیات تجربه</a><a href="#guide">راهنمای انتخاب</a></nav><a href="#collection" class="hub-outline">دنیای خودت را پیدا کن <span>↙</span></a></div></header>
<main id="content">
<section class="hub-hero hub-container">
  <div class="hub-hero-copy"><span class="hub-eyebrow"><i></i> برای زیبایی، یک جهان کافی نیست.</span><h1>هر سلیقه،<br>یک دنیای <em>قشنگ.</em></h1><p>بیوتیا خانه‌ی تجربه‌های متفاوت زیبایی است. هفت دمو با شخصیت مستقل؛ از ظرافت یک مانیکور تا آرامش یک اسپا. وارد دنیایی شوید که بیشتر شبیه شماست.</p><div class="hub-hero-actions"><a href="#collection" class="hub-primary">کشف مجموعه دموها <span>↙</span></a><span class="hub-handnote">با عشق به جزئیات ✦</span></div><div class="hub-stats"><div><strong>۰۷</strong><span>دنیای مستقل</span></div><div><strong>۱۰۰٪</strong><span>فارسی و راست‌چین</span></div><div><strong>∞</strong><span>امکان برای الهام</span></div></div></div>
  <div class="hub-collage" aria-label="نگاهی به دموهای بیوتیا"><div class="collage-orbit"></div><a href="<?php echo esc_url(beautia_studio_url('makeup')); ?>" class="collage-card collage-main"><img src="<?php echo esc_url(beautia_img('glam-portrait.jpg')); ?>" alt="میکاپ مجلسی استودیو میوز" fetchpriority="high" width="600" height="760"><span><b dir="rtl">میوز</b><small>درخشش به سبک شما</small></span></a><a href="<?php echo esc_url(beautia_studio_url('nails')); ?>" class="collage-card collage-small"><img src="<?php echo esc_url(beautia_img('glam-nails.jpg')); ?>" alt="طراحی کریستالی ناخن در نیل" width="400" height="480"><span><b dir="rtl">نیل</b><small>جواهر روی انگشت‌ها</small></span></a><span class="collage-sticker">ساخته‌شده برای<br><b>خاص‌بودنِ شما</b><i>✦</i></span><span class="collage-tag" dir="rtl">هر روز، کمی زیباتر.</span></div>
</section>
<div class="hub-ticker" aria-hidden="true"><div><?php for($i=0;$i<2;$i++): foreach($studios as $s): ?><span dir="rtl"><?php echo esc_html($s['name']); ?></span><i>✦</i><?php endforeach; endfor; ?></div></div>
<section class="hub-collection hub-container" id="collection"><div class="hub-section-head"><div><span class="hub-eyebrow">مجموعه دموها</span><h2>هفت حال‌وهوا.<br><em>کدامش شبیه شماست؟</em></h2></div><p>هر کارت، درِ یک تجربه کامل است.<br>خدمات، تیم، مقالات، نمونه‌کار و رزرو اختصاصی.</p></div>
<div class="hub-filter" role="group" aria-label="فیلتر دموها"><button class="active" data-demo-filter="all" aria-pressed="true">همه دنیاها <small>۰۷</small></button><button data-demo-filter="soft" aria-pressed="false">لطیف و مینیمال</button><button data-demo-filter="bold" aria-pressed="false">جسور و متفاوت</button><button data-demo-filter="calm" aria-pressed="false">آرام و طبیعی</button></div>
<div class="hub-demo-grid">
<?php $i=0; foreach($studios as $demo=>$s): $i++; $group=in_array($demo,array('hair','makeup','barber'),true)?'bold':(in_array($demo,array('spa','clinic'),true)?'calm':'soft'); ?>
<article class="hub-demo-card" data-demo-group="<?php echo $group; ?>" style="--card-accent:<?php echo esc_attr($s['color']); ?>;--card-soft:<?php echo esc_attr($s['soft']); ?>"><a class="demo-preview" href="<?php echo esc_url(beautia_studio_url($demo)); ?>" aria-label="مشاهده دموی <?php echo esc_attr($s['name']); ?>"><div class="preview-chrome"><span dir="rtl"><?php echo esc_html($s['name']); ?> <small>از مجموعه بیوتیا</small></span><i>● ● ●</i></div><div class="preview-visual"><img src="<?php echo esc_url(beautia_img($s['image'])); ?>" alt="<?php echo esc_attr($s['fa']); ?>" loading="lazy" width="800" height="600"><span class="preview-word" dir="rtl"><?php echo esc_html($s['name']); ?></span><span class="preview-caption"><?php echo esc_html($s['tone']); ?></span><span class="preview-open">وارد این دنیا شو ↙</span></div></a><div class="demo-card-info"><div><span class="demo-number"><?php echo beautia_en_to_fa_digits(sprintf('%02d',$i)); ?> /</span><h3><a href="<?php echo esc_url(beautia_studio_url($demo)); ?>"><?php echo esc_html($s['fa']); ?></a></h3><p><?php echo esc_html($s['tone']); ?></p></div><a class="demo-arrow" href="<?php echo esc_url(beautia_studio_url($demo)); ?>" aria-label="ورود به <?php echo esc_attr($s['name']); ?>">↙</a></div><div class="demo-card-tags"><span>رزرو آنلاین</span><span>مجله اختصاصی</span><span>گالری الهام</span></div></article>
<?php endforeach; ?>
<article class="hub-choose-card"><span>✦</span><h3>هنوز انتخاب<br>نکرده‌ای؟</h3><p>از یک حال‌وهوا شروع کن؛ باقی جزئیات، منتظرت هستند.</p><a href="#guide">راهنمای انتخاب دمو ←</a></article>
</div><p class="hub-filter-status" aria-live="polite"></p></section>
<section class="hub-detail" id="details"><div class="hub-container"><div class="hub-section-head"><div><span class="hub-eyebrow">زیبایی، فراتر از ظاهر</span><h2>جزئیاتی که<br><em>تجربه را می‌سازند.</em></h2></div><p>فقط دیدن کافی نیست؛ انتخاب کن، امتحان کن،<br>زمانت را پیدا کن و تجربه را ادامه بده.</p></div><div class="hub-feature-grid"><article><span>۰۱ / انتخاب</span><div class="feature-swatches"><i></i><i></i><i></i><i></i></div><h3>حال‌وهوای تو، پیشنهاد ما</h3><p>یک انتخاب کوچک، یک پیشنهاد از خدمات همان دمو. برای وقتی که می‌دانی چه حسی می‌خواهی، اما هنوز خدمت را انتخاب نکرده‌ای.</p></article><article><span>۰۲ / کشف</span><div class="feature-compare"><img src="<?php echo esc_url(beautia_img('manicure-after-v2.jpg')); ?>" alt="نمونه مانیکور ساخته‌شده برای دمو" loading="lazy"><i>↔</i></div><h3>تغییر را لمس کن</h3><p>مقایسه کشویی قبل و بعد نیل؛ با حرکت دست، دو تصویر هم‌زاویه را کنار هم ببین و در جزئیات دقیق شو.</p></article><article><span>۰۳ / قرار</span><div class="feature-times"><b>۱۰:۰۰</b><b>۱۱:۳۰</b><b>۱۴:۰۰</b></div><h3>زمانی که مال خودت است</h3><p>تقویم هر دمو با خدمات و متخصصان همان مجموعه کار می‌کند؛ زمان خالی را ببین و قدم‌به‌قدم رزرو را ادامه بده.</p></article></div></div></section>
<section class="hub-guide hub-container" id="guide"><div><span class="hub-eyebrow">از کجا شروع کنیم؟</span><h2>زیبایی،<br>به زبانِ <em>شما.</em></h2><p>برای کشف مجموعه، عجله نکنید. هر دمو را مثل یک فضای واقعی ببینید؛ نور، رنگ، جزئیات و شیوه انتخاب خدمت.</p><a class="hub-primary" href="<?php echo esc_url(beautia_studio_url('nails')); ?>">از نیل شروع کنیم ↙</a></div><div class="guide-list"><details open><summary><span>۰۱</span> من ظرافت و رنگ‌های لطیف دوست دارم <i>+</i></summary><p>نیل و آتلیه نگاه با فرم‌های نرم، رنگ‌های نود و جزئیات کوچک، نقطه شروع خوبی هستند.</p><a href="<?php echo esc_url(beautia_studio_url('nails')); ?>">کشف نیل ←</a></details><details><summary><span>۰۲</span> دنبال حال‌وهوای جسور و خاص هستم <i>+</i></summary><p>خانه مو، استودیو میوز و پیرایش اُک با تضاد، رنگ و تایپوگرافی شاخص طراحی شده‌اند.</p><a href="<?php echo esc_url(beautia_studio_url('hair')); ?>">کشف خانه مو ←</a></details><details><summary><span>۰۳</span> آرامش و سادگی برایم مهم‌تر است <i>+</i></summary><p>اسپای سوما و کلینیک بیوتیا از فضای خالی، نور و پالت‌های طبیعی برای ساختن تجربه‌ای آرام استفاده می‌کنند.</p><a href="<?php echo esc_url(beautia_studio_url('spa')); ?>">کشف اسپای سوما ←</a></details></div></section>
<section class="hub-end"><div class="hub-container"><span>✦</span><h2>یک کلیک تا دنیای قشنگ‌تر.</h2><a href="#collection">مجموعه را دوباره ببین ↖</a></div></section>
</main><footer class="hub-footer hub-container"><a class="hub-brand" href="<?php echo esc_url(home_url('/')); ?>"><span>✦</span><strong>بیوتیا<small dir="rtl">مجموعه بیوتیا</small></strong></a><p>با سلیقه ساخته شده، برای سلیقه‌های متفاوت.</p><small>تمام اطلاعات، تصاویر و نوبت‌ها برای نمایش دمو هستند.</small></footer></div><?php wp_footer(); ?></body></html>
